# RTAP — Real-Time Autonomous Perception (AGPL-3.0)

# Builds rtap/rtap:latest-jetson-jetpack5 image on DockerHub 
# Supports JetPack5.1.2 for YOLO on Jetson Xavier NX, AGX Xavier, AGX Orin, Orin Nano and Orin NX

# Start FROM https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-jetpack
FROM nvcr.io/nvidia/l4t-jetpack:r35.4.1

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    UV_BREAK_SYSTEM_PACKAGES=1

# Downloads to user config dir
ADD  \
     \
    /root/.config/RTAP/

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git python3-pip libopenmpi-dev libopenblas-base libomp-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create working directory
WORKDIR /rtap

# Copy contents and configure dependencies
COPY . .
RUN sed -i'' -e 's/"opencv-python/"opencv-python-headless/' pyproject.toml
ADD  .

# Replace pyproject.toml TF.js version with 'tensorflowjs>=3.9.0' for JetPack5 compatibility and install packages
RUN sed -i 's/^\( *"tensorflowjs\)>=.*\(".*\)/\1>=3.9.0\2/' pyproject.toml && \
    python3 -m pip install --upgrade pip uv

# Pip install onnxruntime-gpu, torch, torchvision and rtap, then remove build files
RUN uv pip install --system \
     \
     \
     && \
    # Need lower version of 'numpy' for TensorRT export
    uv pip install --system numpy==1.23.5 && \
    uv pip install --system -e ".[export]" && \
    # Remove extra build files
    rm -rf *.whl /root/.config/RTAP/persistent_cache.json

# Usage --------------------------------------------------------------------------------------------------------------

# Production builds: 
# Example (build): t=rtap/rtap:latest-jetson-jetpack5 && docker build --platform linux/arm64 -f docker/Dockerfile-jetson-jetpack5 -t $t .
# Example (push): docker push $t
# Example (pull): t=rtap/rtap:latest-jetson-jetpack5 && docker pull $t
# Example (run-jetson): docker run -it --ipc=host --runtime=nvidia $t
# Example (run-jetson-with-volume): docker run -it --ipc=host --runtime=nvidia -v "$PWD/shared/datasets:/datasets" $t
