# RTAP — Real-Time Autonomous Perception (AGPL-3.0)

# Builds rtap/rtap:latest-jetson-jetpack6 image on DockerHub 
# Supports JetPack6.1 for YOLO on Jetson AGX Orin, Orin NX and Orin Nano Series

# Start FROM https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-jetpack
FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    UV_BREAK_SYSTEM_PACKAGES=1

# Downloads to user config dir
ADD  \
     \
    /root/.config/RTAP/

# Install dependencies and cleanup
ADD https://developer.download.nvidia.com/compute/cudss/0.7.1/local_installers/cudss-local-tegra-repo-ubuntu2204-0.7.1_0.7.1-1_arm64.deb .
RUN dpkg -i cudss-local-tegra-repo-ubuntu2204-0.7.1_0.7.1-1_arm64.deb && \
    cp /var/cudss-local-tegra-repo-ubuntu2204-0.7.1/cudss-*-keyring.gpg /usr/share/keyrings/ && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    git python3-pip libopenmpi-dev libopenblas-base libomp-dev cudss && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Upgrade TensorRT from 10.3.0 to 10.7.0 to fix INT8 + end2end build issues on JetPack 6
# 
ADD https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb .
RUN dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get install -y tensorrt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* cuda-keyring_1.1-1_all.deb

# Create working directory
WORKDIR /rtap

# Copy contents and configure dependencies
COPY . .
RUN sed -i'' -e 's/"opencv-python/"opencv-python-headless/' pyproject.toml
ADD  .

# Pip install onnxruntime-gpu, torch, torchvision and rtap, then remove build files
RUN python3 -m pip install --upgrade pip uv && \
    uv pip install --system \
     \
     \
     && \
    uv pip install --system -e ".[export]" && \
    # Remove extra build files
    rm -rf *.whl /root/.config/RTAP/persistent_cache.json

# Usage --------------------------------------------------------------------------------------------------------------

# Production builds: 
# Example (build): t=rtap/rtap:latest-jetson-jetpack6 && docker build --platform linux/arm64 -f docker/Dockerfile-jetson-jetpack6 -t $t .
# Example (push): docker push $t
# Example (pull): t=rtap/rtap:latest-jetson-jetpack6 && docker pull $t
# Example (run-jetson): docker run -it --ipc=host --runtime=nvidia $t
# Example (run-jetson-with-volume): docker run -it --ipc=host --runtime=nvidia -v "$PWD/shared/datasets:/datasets" $t
